### ISSUE TITLE
getting a maven error

### ISSUE THREAD

**Issue by orrgal1** [algolia/algoliasearch-client-java-legacy#1]
[WARNING] The POM for com.algolia:algoliasearch:jar:1.2.3 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model
[FATAL] Non-parseable POM /Users/tom/.m2/repository/com/algolia/algoliasearch/1.2.3/algoliasearch-1.2.3.pom: end tag name </head> must be the same as start tag <meta> from line 4 (position: TEXT seen ...</style>\n  </head>... @49:10)  @ line 49, column 10

**Comment by orrgal1** [comment]
1.2.2 is ok

**Comment by redox** [comment]
We had some issues with the 1.2.3 release; seems our tag was not well set. We've just re-set the 1.2.3 tag. Do you mind trying again? (Maybe removing `/Users/tom/.m2/repository/com/algolia/algoliasearch/1.2.3` first)

Or just upgrade to 1.3.1, should be OK and no API breaks.

Let me know how it goes!
