### ISSUE TITLE
deleteObject not working when DSN is on

### ISSUE THREAD

**Issue by shigoku** [algolia/algoliasearch-client-java-legacy#17]
If I understand well, the hosts are picked based on the whether build is true/false

https://github.com/algolia/algoliasearch-client-java/blob/master/src/main/java/com/algolia/search/saas/APIClient.java#L797

```
List<String> hosts = build ? this.buildHostsArray : this.queryHostsArray;
```

but here on the deleteObject method, the value of build is set to false.

https://github.com/algolia/algoliasearch-client-java/blob/master/src/main/java/com/algolia/search/saas/Index.java#L367

```
public JSONObject deleteObject(String objectID) throws AlgoliaException {
        if (objectID == null || objectID.length() == 0) {
            throw new AlgoliaException("Invalid objectID");
        }
        try {
            return client.deleteRequest("/1/indexes/" + encodedIndexName + "/" + URLEncoder.encode(objectID, "UTF-8"), false);
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
    }
```

Which leads to:

```
{"message":"This host is read-only, write operation are not accepted","status":403}”
```

-_-

**Comment by Nagriar** [comment]
Hi @shigoku,

We just released the version 1.6.4 with this fix, thanks a lot for your feedback.

Best regards
