### ISSUE TITLE
minimumAroundRadius missing

### ISSUE THREAD

**Issue by florent-blanvillain** [algolia/algoliasearch-client-java-legacy#21]
Hi,

Is there a workaround to quickly add this parameter without having to fork ?

**Comment by florent-blanvillain** [comment]
I close this issue because I misunderstood the parameter, I don't need it.

**Comment by PLNech** [comment]
Hi, thank you reporting this!

Even if you don't need it now, this is indeed a missing parameter. 
I'll reopen the issue and take care of it!
