### ISSUE TITLE
v2 wish list

### ISSUE THREAD

**Issue by ElPicador** [algolia/algoliasearch-client-java-legacy#24]
Before starting the dev of the v2 of the Java client, let's have a list of things we might want to have.
- Java 8 only support
- Async, Future, etc API
- Keep the sync API
- Changing the HTTP client?
  - Having the [Google HTTP client](https://developers.google.com/api-client-library/java/) might be an easy way to support GAE.
  - Having one that support DNS resolution timeouts
- Adding JSON serialization/deserialization (like the scala client)
- Having jackson as the JSON serializer

**Comment by ElPicador** [comment]
@redox, @PLNech, @clement-leprovost-algolia, @Nagriar.

Any comments/ideas/beers?

**Comment by redox** [comment]
> Any comments/ideas/beers?

I think your list is definitely covering all what we need 👍 🍻

**Comment by clement-leprovost** [comment]
My 2 cents:
- If you want to use a non-built-in HTTP engine, you should make it pluggable, so that (1) an alternative engine can be used and (2) the external dependency is optional. Otherwise, I would prefer keeping the built-in engine.
- If you implement an async API returning futures, please make sure they are cancellable.
- Java 8 only: are you sure you want to drop earlier Java versions?

**Comment by Nagriar** [comment]
@ElPicador The idea to merge the android and java api client is not possible so?

The public updates of 1.7 stopped in April 2015. The old apps will still be able to use the v1 of the api client which is compatible with 1.6+.

**Comment by clement-leprovost** [comment]
@Nagriar We discussed merging the Android & Java clients, but we came to the conclusion that it would be very, very cumbersome, and that the benefits of code sharing would likely be overcome by the overhead of merging. In particular:
- Android imposes specific rules for usage of the UI thread. We use Android-specific classes (`AsyncTask` among others) to honour them.
- Java 8 is not yet supported on Android (will be in Android N, officially due in Q3 2016).
- The binary size of the compiled Android client must be as small as possible. We therefore need to minimize dependencies.
- Android has built-in JSON support, so we need to use it to offer a consistent interface, whereas plain Java has not.
- The Android client must eventually support the offline SDK, which comes with very specific packaging requirements (using Gradle product flavors). The plain Java client should be package manager agnostic.
- The Android client is a front-end client, so we do not wish to include operations requiring the admin API key.

Each of those obstacles could have a workaround, but all together, this makes it too much of a mess to really bother, in my opinion.

**Comment by ElPicador** [comment]
@clement-leprovost-algolia We already use a non-built-in HTTP client: The apache http client. SO no worries here.

**Comment by ElPicador** [comment]
Here is my take on google-http-client:
- 👍 
  - Works on GAE
  - Has sync & async methods
- 👎 
  - Doesn't handle the DNS timeouts correctly, unless you choose ApacheHttpClient as a backend and implement a custom DNS resolver (which we don't want to)
  - Depends on an old version of ApacheHttpClient 4, and the version 5 is on it's way

We also could use the same http client as in Scala (async-http-client), which handles correctly the DNS timeouts, but it has no sync methods 😢 

Anyone an idea on which way to go?

**Comment by ElPicador** [comment]
One other way would be to add async-http-client as a backend of google-http-client

**Comment by ElPicador** [comment]
Project migrated to https://github.com/algolia/algoliasearch-client-java-2
