### ISSUE TITLE
java.net.ProxySelector is a restricted class. Please see the Google App Engine developer's guide for more details.

### ISSUE THREAD

**Issue by Edijae** [algolia/algoliasearch-client-java-legacy#248]
I need to use Algolia in my google app engine backend but when i call the below code 

`APIClient client = new APIClient("BXXXXXX", "xxxxxxxxxxxxxxxxxxxxxx");`

I get the below error

`Uncaught exception from servlet java.lang.NoClassDefFoundError: java.net.ProxySelector is a restricted class. Please see the Google App Engine developer's guide for more details. at com.google.apphosting.runtime.security.shared.stub.java.net.ProxySelector.<clinit>(ProxySelector.java) at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:1136) at com.algolia.search.saas.APIClient.<init>(APIClient.java:165) at com.algolia.search.saas.APIClient.<init>(APIClient.java:137) at com.algolia.search.saas.APIClient.<init>(APIClient.java:123)`

**Comment by Edijae** [comment]
I was able to solve the problem by using version 1.11.0. This algolia guide on Install section(https://github.com/algolia/algoliasearch-client-java#install), gives an example of version 1.6 which was throwing the above error. 
I think the guide should be updated to show examples using version 1.11.0 instead of version 1.6

> Install
> 
> If you're using Maven, add the following dependency to your pom.xml file:
> ```
> 
> <dependency>
>     <groupId>com.algolia</groupId>
>     <artifactId>algoliasearch</artifactId>
>     <version>[1.6,]</version>
> </dependency>
> ```

**Comment by ElPicador** [comment]
Thanks for the report. I've updated the documentation
