### ISSUE TITLE
"Resource does not exist" exception when initIndex().addUserKey() is called

### ISSUE THREAD

**Issue by kpankowski** [algolia/algoliasearch-client-java-legacy#3]
Hi,

I'm not sure if this is a bug, but if not then it looks to me that it is an small inconsistency in API.

When you call initIndex() method you might expect that "index" will be created/initialized, and all operations on Index will not return "404" (Index does not exist).

It looks like this is valid for adding an object to index: initIndex().addObject(), but unfortunately for initIndex().addUserKey() we get AlgoliaException with code 404.

Is there any possibility to create an UserKey without adding first object to index via API?

**Comment by redox** [comment]
Hi @kpankowski,

actually that's the expected behavior. The `initIndex` method doesn't create the index, it just initializes the `Index` java object. The index will be created after the first "write" operation, no need to "create it".

What I'm used to do is:

``` java
Index index = client.initIndex("my_index");
JSONObject task = index.setSettings(new JSONObject()); // set empty settings to create the index
index.waitTask(task. getString("taskID")); // wait until the index is actually created
/// FIXME: add user keys, etc....
```

Does that fit your needs?

**Comment by kpankowski** [comment]
Hi @redox,

Thanks. Your solutions also works for me. 

It was clear for me that `initIndex` doesn't create the index in the backend. The only problem was to distinguish methods that create index in the background like `index.setSettings` or `index.addObject` from methods that behave differently eg `index.addUserKey`.

**Comment by redox** [comment]
That's right; maybe we should create the index while creating a new user key as well -> it's not really different than an `{add,save}Object`. I'll share your point with the team. Thank you for the feedback!
